// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd8EGFiCBroIV6T39yTSaNrOtzhXYkVEo',
    appId: '1:92065715551:web:0d593377e4a017f1aa52ea',
    messagingSenderId: '92065715551',
    projectId: 'my-travels-8d595',
    authDomain: 'my-travels-8d595.firebaseapp.com',
    storageBucket: 'my-travels-8d595.appspot.com',
    measurementId: 'G-NFDR40ECGM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeYGML-Ny42sk2rjG7wGwJOoCCwMbTL6g',
    appId: '1:92065715551:android:ce8898b6c6bd6879aa52ea',
    messagingSenderId: '92065715551',
    projectId: 'my-travels-8d595',
    storageBucket: 'my-travels-8d595.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_M-0hY4XdywieklMwF9bnfhkJqa9rJgk',
    appId: '1:92065715551:ios:8d09725009987f88aa52ea',
    messagingSenderId: '92065715551',
    projectId: 'my-travels-8d595',
    storageBucket: 'my-travels-8d595.appspot.com',
    iosClientId: '92065715551-v823sednpag2glafhrql5h2qjbh8m9mk.apps.googleusercontent.com',
    iosBundleId: 'com.example.myTravels',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_M-0hY4XdywieklMwF9bnfhkJqa9rJgk',
    appId: '1:92065715551:ios:2daceff40cf9558daa52ea',
    messagingSenderId: '92065715551',
    projectId: 'my-travels-8d595',
    storageBucket: 'my-travels-8d595.appspot.com',
    iosClientId: '92065715551-n8pgrd54065svhm3477p2096umrelqbe.apps.googleusercontent.com',
    iosBundleId: 'com.example.myTravels.RunnerTests',
  );
}
